version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orders_app

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: orders_test